FROM jenkins/jenkins:2.509-slim-jdk21

# Python + PIP + venv
USER root
RUN apt update && apt install python3-pip python3.11-venv -y
USER jenkins
# Initalize Jenkins with JCasC and plugins, to preconfigure everything
RUN jenkins-plugin-cli --plugins configuration-as-code job-dsl git \
    locale workflow-job workflow-cps pipeline-graph-view
COPY scheduler_config/jenkins.yaml /var/jenkins_home/jenkins.yaml
# Disable first setup UI
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

EXPOSE 8080